if: type IN (push)
branches:
  only:
  - master
language: python
python:
  - 2.7
# caching takes longer than installing
# cache:
#  pip: true
#  directories:
#    - /home/travis/.nvm/versions/node/v7.4.0/
# nothin sensitive there
env:
  - SURGE_LOGIN=x3domsurge@gmail.com SURGE_TOKEN=66e909183b62ec798569f7ffb3e95d8a SURGE_DOMAIN=x3dom-dev.surge.sh
install:
  - "# **********************************************"
  - "# *                                            *"
  - "# *                                            *"
  - "# *     HTTP://X3DOM-DEV.SURGE.SH/LATEST       *"
  - "# *                                            *"
  - "# *     for this and recent master builds      *"
  - "# *                                            *"
  - "# *                                            *"
  - "# **********************************************"
  - echo -e "\e[0;45m http://${SURGE_DOMAIN}/latest \e[0m for build result"
  - pip install argparse
  - npm install -g surge
addons:
  apt:
    packages:
    - tree
    #- python-sphinx
script:
  - cd doc
  - chmod a+x ./jsdoc-releases-3.1/jsdoc
  - ./jsdoc-releases-3.1/jsdoc -c jsdoc.conf
  - cd ../
  - mkdir -p deploy/latest
  - mv doc/out deploy/latest/doc
  - python manage.py --build > build.log
after_success:
  - # only get build dirs, do not descend into doc
  - ( wget -nv -e robots=off -r -nH -np -l 2 -I /build_? -P deploy $SURGE_DOMAIN; exit 0 )
  - # go into build dirs and get marks
  - # ( wget -nv -e robots=off -r -nH -np -l 2 -R js,css -I /build_? -S -P deploy $SURGE_DOMAIN; exit 0 )
  - # get build no for latest
  - ( wget -nv -e robots=off -r -nH -np --accept-regex='build_.+' ${SURGE_DOMAIN}/latest/index.html; exit 0 )  
  - cp dist/x3dom.* dist/x3dom-full.* deploy/latest
  - >
    lastbuild=$(ls latest/build_?); lastbuild=${lastbuild: -1}
  - build=$(((lastbuild+1) % 10))
  - # some convenience variables
  - >
    BUILD=build_$build
    COMMIT_MARK=commit_$TRAVIS_COMMIT PR_MARK=PR_NUMBER_$TRAVIS_PULL_REQUEST
    COMMIT_URL=https://github.com/${TRAVIS_REPO_SLUG}/commit
    PR_URL=https://github.com/${TRAVIS_REPO_SLUG}/pull
  - cd deploy
  - touch latest/$BUILD
  - touch "latest/$(date +%F\ %R)"
  - touch latest/$COMMIT_MARK
  - touch latest/$PR_MARK
  - rm -rf $BUILD
  - cp -r latest $BUILD
  - tree -L 3 -r -I index.html -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} commit ${TRAVIS_COMMIT} build:" ./ > index.html
  - "# link to commit and PR on github"
  - sed -i "s=./.*commit_\(.*commit\)=${COMMIT_URL}/\1=" index.html
  - sed -i "s=./.*PR_NUMBER_\(.*PR\)=${PR_URL}/\1=" index.html
  - tree -I index.html -h -C -h -H '.' -T "title" ./$BUILD > ./${BUILD}/index.html
  - "# link title to PR and commit on github"
  - sed -i "s-<h1>.*</h1>-<h1><a href=\"${PR_URL}/${TRAVIS_PULL_REQUEST}\">PR ${TRAVIS_PULL_REQUEST}</a> <a href=\"${COMMIT_URL}/${TRAVIS_COMMIT}\">commit ${TRAVIS_COMMIT}</a></h1>-" ./${BUILD}/index.html
  - tree -I index.html -h -C -h -H '.' -T "title" ./latest > ./latest/index.html
  - "# link title to PR and commit on github"
  - sed -i "s-<h1>.*</h1>-<h1><a href=\"${PR_URL}/${TRAVIS_PULL_REQUEST}\">PR ${TRAVIS_PULL_REQUEST}</a> <a href=\"${COMMIT_URL}/${TRAVIS_COMMIT}\">commit ${TRAVIS_COMMIT}</a></h1>-" ./latest/index.html
  - surge --project ./ --domain $SURGE_DOMAIN
  - "# just for logging purposes"
  - du -ah ./
  - env
  - cat ../build.log
