language: python
python:
  - 2.7
# caching takes longer than installing
# cache:
#  pip: true
#  directories:
#    - /home/travis/.nvm/versions/node/v7.4.0/
# nothin sensitive there
env:
  - SURGE_LOGIN=x3domsurge@gmail.com SURGE_TOKEN=66e909183b62ec798569f7ffb3e95d8a SURGE_DOMAIN=x3dom-builds.surge.sh
install:
  - "# **********************************************"
  - "# *                                            *"
  - "# *                                            *"
  - "# *     HTTP://X3DOM-BUILDS.SURGE.SH/LATEST    *"
  - "# *                                            *"
  - "# *         for this and recent builds         *"
  - "# *                                            *"
  - "# *                                            *"
  - "# **********************************************"
  - echo -e "\e[0;45m http://${SURGE_DOMAIN}/latest \e[0m for build result"
  - pip install argparse
  - npm install -g surge
addons:
  apt:
    packages:
    - tree
script:
  - python manage.py --build > build.log
  - mkdir -p deploy/latest
after_success:
  - ( wget -e robots=off -r -nH -np -l 1 -X /latest,/build_?? -S -P deploy $SURGE_DOMAIN; exit 0 )
  - ( wget -e robots=off -r -nH -np --accept-regex='build_.+' -S ${SURGE_DOMAIN}/latest/index.html; exit 0 )  
  - cp dist/x3dom.* dist/x3dom-full.* deploy/latest
  - >
    lastbuild=$(ls latest/build_?); lastbuild=${lastbuild: -1}
  - build=$(((lastbuild+1) % 10))
  - cd deploy
  - touch latest/build_$build
  - touch latest/$(date +%F_%R)
  - touch latest/commit_$TRAVIS_COMMIT
  - touch latest/PR_NUMBER_$TRAVIS_PULL_REQUEST
  - rm -rf build_$build
  - cp -r latest build_$build
  - tree -r -I index.html -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} build:" ./ > index.html
  - "# link to commit and PR on github"
  - sed -i "s=./.*commit_\(.*commit\)=https://github.com/${TRAVIS_REPO_SLUG}/commit/\1=" index.html
  - sed -i "s=./.*PR_NUMBER_\(.*PR\)=https://github.com/${TRAVIS_REPO_SLUG}/pull/\1=" index.html
  - tree -I index.html -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} commit ${TRAVIS_COMMIT}:" ./build_$build > ./build_${build}/index.html
  - "# link to commit and PR on github"
  - sed -i "s=./commit_${TRAVIS_COMMIT}=https://github.com/${TRAVIS_REPO_SLUG}/commit/${TRAVIS_COMMIT}=" ./build_${build}/index.html
  - sed -i "s=./PR_NUMBER_${TRAVIS_PULL_REQUEST}=https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}=" ./build_${build}/index.html
  - tree -I index.html -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} build/latest:" ./latest > ./latest/index.html
  - "# link to commit and PR on github"
  - sed -i "s=./commit_${TRAVIS_COMMIT}=https://github.com/${TRAVIS_REPO_SLUG}/commit/${TRAVIS_COMMIT}=" ./latest/index.html
  - sed -i "s=./PR_NUMBER_${TRAVIS_PULL_REQUEST}=https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}=" ./latest/index.html
  - surge --project ./ --domain $SURGE_DOMAIN
  - "# just for logging purposes"
  - du -ah ./
  - env
  - cat ../build.log
