language: python
python:
  - 2.7
install:
  - pip install argparse
script:
  - python manage.py --build
after_script:
  - du -ah dist
  - env
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PUBLIC_REPO_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    all_branches: true
