language: python
python:
  - 2.7
install:
  - pip install argparse
  - npm install -g surge
addons:
  apt:
    packages:
    - tree
script:
  - mkdir -p deploy/dev-$TRAVIS_COMMIT
#  - ( wget -e robots=off -r -nH -np -X /latest -S -P deploy http://x3dom-dev.surge.sh; exit 0 ) 
  - python manage.py --build
after_success:
  - cp dist/x3dom.* dist/x3dom-full.* deploy/dev-$TRAVIS_COMMIT
 # - cp dist/x3dom.* dist/x3dom-full.* deploy/latest
  - tree -h -C -D -H '.' -R -L 3 -T "x3dom PR ${TRAVIS_PULL_REQUEST} build:" deploy/ > deploy/index.html
  - ln -s ./deploy/dev-$TRAVIS_COMMIT ./deploy/latest
  - ls -la deploy/*
  - mv deploy/dev-${TRAVIS_COMMIT}/*html deploy/dev-${TRAVIS_COMMIT}/index.html
  - du -ah deploy
  - env
  - surge --project ./deploy --domain x3dom-dev.surge.sh
