language: python
python:
  - 2.7
# nothin sensitive there
env:
  - SURGE_LOGIN=x3domsurge@gmail.com SURGE_TOKEN=66e909183b62ec798569f7ffb3e95d8a SURGE_DOMAIN=x3dom-builds.surge.sh
install:
  - echo -e "\e[0;45m http://${SURGE_DOMAIN}/latest \e[0m for build result"
  - pip install argparse
  - npm install -g surge
addons:
  apt:
    packages:
    - tree
script:
  - python manage.py --build > build.log
  - mkdir -p deploy/latest
after_success:
  - ( wget -e robots=off -r -nH -np -X /latest -S -P deploy $SURGE_DOMAIN; exit 0 )
  - ( wget -e robots=off -r -nH -np --accept-regex='build_.+' -S ${SURGE_DOMAIN}/latest/index.html; exit 0 )  
  - cp dist/x3dom.* dist/x3dom-full.* deploy/latest
  - >
    lastbuild=$(ls latest/build_?); lastbuild=${lastbuild: -1}
  - build=$((lastbuild+1 % 10))
  - touch deploy/latest/build_$build
  - touch deploy/latest/$(date +%F_%R)
  - rm -rf deploy/build_$build
  - rm -rf deploy/dev*
  - cp -r deploy/latest deploy/build_$build
  - touch deploy/build_${build}/commit_$TRAVIS_COMMIT
  - tree -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} build:" deploy/ > deploy/index.html
  - tree -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} commit ${TRAVIS_COMMIT}:" deploy/build_$build > deploy/build_${build}/index.html
  - tree -h -C -h -H '.' -T "x3dom PR ${TRAVIS_PULL_REQUEST} build/latest:" deploy/latest > deploy/latest/index.html
  - surge --project ./deploy --domain ${SURGE_DOMAIN}
  - du -ah deploy
  - env
  - cat build.log
  
