language: python
python:
  - 2.7
install:
  - pip install argparse
script:
  - python manage.py --build
after_script:
  - du -ah dist
  - env
deploy:
  provider: surge
  skip_cleanup: true
  project: ./dist/
  domain: x3dom-dev.surge.sh
  on:
    all_branches: true
