language: python
python:
  - 2.7
install:
  - pip install argparse
script:
  - python manage.py --build
  - mkdir -p deploy/dev-$TRAVIS_COMMIT
  - cp dist/x3dom.* dist/x3dom-full.* deploy/dev-$TRAVIS_COMMIT
  - ln -s deploy/dev-$TRAVIS_COMMIT deploy/latest
  - ls -latr deploy/* > deploy/index.html
after_script:
  - du -ah deploy
  - env
deploy:
  provider: surge
  skip_cleanup: true
  project: ./deploy/
  domain: x3dom-dev.surge.sh
  on:
    all_branches: true
