name: X3DOM lint

on:
  push:
    branches-ignore:
      - master

jobs:
  ESLINTFIX:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: npm run lint
      continue-on-error: true
      run: npm run lint -o eslint.err
    - run: echo eslint.err
    - run: npm run lint-fix
    - run: grep x3dom/src eslint.err
    - run: cat `grep x3dom/src eslint.err`
      
    
