name: X3DOM lint fixer

on:
  push:
    branches-ignore:
      - master

jobs:
  ESLINTFIX:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: npm run lint
      continue-on-error: true
      run: npm run lint > eslint.err
    - run: cat eslint.err
    - run: (for f in `grep x3dom/src eslint.err`; do cp $f $f.orig; echo $f; done && exit 0)
    - run: find /home/runner/work/x3dom/x3dom/src -name '*orig'
    - run: npm run lint-fix
    - run: mkdir fixed
    - name: copy and prepare fixes
      env:
        REPORT: eslint report
        DIFFOUTPUT: diff output
      shell: /bin/bash {0}
      run: |        
        for f in `grep x3dom/src eslint.err`; do cat $f >> eslint.err; cp $f fixed; diff -u $f.orig $f >> diffs; done
        REPORT="$(cat eslint.err)"
        REPORT="${REPORT//'%'/'%25'}"
        REPORT="${REPORT//$'\n'/'%0A'}"
        REPORT="${REPORT//$'\r'/'%0D'}" 
        echo "::set-env name=REPORT::$REPORT"
        DIFFOUTPUT="$(cat diffs)"
        DIFFOUTPUT="${DIFFOUTPUT//'%'/'%25'}"
        DIFFOUTPUT="${DIFFOUTPUT//$'\n'/'%0A'}"
        DIFFOUTPUT="${DIFFOUTPUT//$'\r'/'%0D'}" 
        echo "$DIFFOUTPUT"
        echo "::set-env name=DIFFOUTPUT::$DIFFOUTPUT"
      continue-on-error: true
    - name: upload fixed files
      uses: actions/upload-artifact@v1
      with:
        name: eslint fix
        path: fixed
    - run: echo "$DIFFOUTPUT"
    - name: Create diff comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          diff:
          ```
          ${{ env.DIFFOUTPUT }}
          ```
    - name: Create lint comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          eslint report:
          ```
          ${{ env.REPORT }}
          ```
