name: X3DOM lint

on:
  push:
    branches-ignore:
      - master

jobs:
  ESLINT:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: npm run lint
      continue-on-error:
      run: npm run lint
    - run: npm run lint-fix
    
