name: X3DOM lint

on:
  push:
    branches-ignore:
      - master

jobs:
  ESLINTFIX:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: npm run lint
      continue-on-error: true
      run: npm run lint > eslint.err
    - run: cat eslint.err
    - run: for f in `grep x3dom/src/eslint.err`; do cp $f $f.orig; echo $f; done
    - run: npm run lint-fix
    - run: grep x3dom/src eslint.err
    - run: for f in `grep x3dom/src/eslint.err`; do diff $f $f.orig; done
    - run: cat `grep x3dom/src eslint.err`
    
